/**
 * jcurses.event. 
 */

package jcurses.event;

import jcurses.widgets.Widget;

/**
*  Instances of this class are generated by widgets if an user makes an action,
*  for example pushes a button or selects a menu item.
*/
public class ActionEvent extends Event {
	
	/**
	 * Constructor.
	 * @param source the widget giving rise 
	 * to the event.
	 */
	public ActionEvent(final Widget source) {
		super(source);
	}

}
