/**
 * jcurses.event package.
 */
package jcurses.event;

import jcurses.widgets.Widget;

/**
 * Instances of this class are generated by widgets, that manage a value, an
 * example is the text field widget. Such events are generated, if an user has
 * modified the value associated with the widget.
 */
public class ValueChangedEvent extends Event {

	/**
	 * Constructor of event.
	 * @param source the widget that triggered the event.
	 */
	public ValueChangedEvent(final Widget source) {
		super(source);
	}

}
